# CUDA
cuda_devices: '0'   # multi-gpu training is available

# result
ckpt_root: 'ckpt_root/'
ckpt: 'ckpt'

# dataset
dataset: 'modelnet40' 

# train
lr: 0.01
momentum: 0.9
weight_decay: 0.0005
batch_size: 64
max_epoch: 150
milestones: [30, 60]
gamma: 0.1
